vulnerabilities:
  - id: CVE-2025-64756
    statement: not patched in source
    expired_at: 2026-03-30
  - id: CVE-2026-23745
    statement: not patched in source
    expired_at: 2026-03-30
  - id: CVE-2026-23745
    statement: not patched in source
    expired_at: 2026-03-30
  - id: CVE-2026-23950
    statement: not patched in source
    expired_at: 2026-03-30
  - id: CVE-2026-23950
    statement: not patched in source
    expired_at: 2026-03-30
  - id: CVE-2026-24842
    statement: not patched in source
    expired_at: 2026-03-30
  - id: CVE-2026-24842
    statement: not patched in source
    expired_at: 2026-03-30
