misconfigurations:
  - id: AVD-DS-0002
    statement: Lambda creates a docker USER with least-privilege permissions.
  - id: AVD-DS-0017
    statement: Package manager update should always have install
vulnerabilities:
  - id: CVE-2025-13034
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-14017
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-14524
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-14819
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-15079
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-15224
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-15468
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-66199
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-68160
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-69418
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-69419
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-69420
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-69421
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2026-22795
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2026-22796
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2026-24882
    statement: Waiting for team to return
    expired_at: 2026-03-20
