misconfigurations:
  - id: AVD-DS-0002
    statement: Lambda creates a docker USER with least-privilege permissions.
  - id: AVD-DS-0017
    statement: Package manager update should always have install
vulnerabilities:
  - id: CVE-2024-11053
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-0167
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-0913
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-10148
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-10966
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-11065
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-11563
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-13034
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-13151
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-13601
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-14017
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-14087
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-14524
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-14819
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-15079
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-15224
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-15467
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-15468
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-22870
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-22871
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-22872
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-22873
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-4673
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-47906
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-47907
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-47912
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-47912
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-58183
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-58183
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-58185
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-58185
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-58186
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-58186
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-58187
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-58187
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-58188
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-58188
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-58189
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-58189
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-61723
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-61723
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-61724
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-61724
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-61725
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-61725
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-61726
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-61726
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-61727
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-61727
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-61728
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-61728
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-61729
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-61729
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-61730
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-61730
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-61731
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-66199
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-68119
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-68121
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-68121
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-68160
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-68973
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-69418
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-69419
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-69420
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-69421
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-8732
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2025-9086
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2026-0989
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2026-0990
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2026-0992
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2026-22795
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2026-22796
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: CVE-2026-24882
    statement: Waiting for team to return
    expired_at: 2026-03-20
  - id: GHSA-fv92-fjc5-jj9h
    statement: Waiting for team to return
    expired_at: 2026-03-20
