misconfigurations:

vulnerabilities:
  - id: CVE-2025-58183
    statement: Waiting for team to return
    expired_at: 2026-02-20
  - id: CVE-2025-61729
    statement: Waiting for team to return
    expired_at: 2026-02-20
  - id: CVE-2025-61726
    statement: Waiting for team to return
    expired_at: 2026-02-20
  - id: CVE-2025-61728
    statement: Waiting for team to return
    expired_at: 2026-02-20
